import React from 'react';
import ReactDOM from 'react-dom';

//Create a new component that produce some html
//same as function()
const App = () => {
  return <div>Hi!</div>;
}


//put html generated by this component into the browser DOM
ReactDOM.render(<App />, document.querySelector('.container'));
